changeQuoting: Refactoring: Long parsing

diff --git a/bin/changeQuoting b/bin/changeQuoting
--- a/bin/changeQuoting
+++ b/bin/changeQuoting
@@ -12,11 +12,22 @@ HELPTEXT
 }
 quoter=bashQuote
 separator=' '
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --posix)		shift; quoter=posixQuote;;
-    --separator|-s)	shift; separator="$1"; shift;;
-esac
+isOneline=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--posix)	shift; quoter=posixQuote;;
+	--separator|-s)	shift; separator="$1"; shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
+if [ $# -ne 0 ]; then
+    printUsage "$0" >&2
+    exit 2
+fi
 
 posixQuote()
 {
