commandName: Reimplementation: Let eval() parse the VAR=VAL assignments
My glob/regexp-based parsing only handled simple cases, but failed to correctly parse complex assignments, like this:
> GIT_SELECTEDCOMMIT_COMMAND='log --topo-order --diff-merges=first-parent --no-patch --grep '\''^\(fixup\|amend\|squash\)! '\'' --invert-grep' git-selectedcommit-command --pass-file-args --allow-outside-workingcopy correct --max-count 7
Unfortunately, in debugging, these happen quite frequently. Only Bash itself can reliably parse those. On the other hand, with eval() there's the danger of command executions, which we don't want.
Luckily, all we're interested in is the command name itself, so we can relentlessly slaughter and mangle anything else.
- replace command separators (; && ||) with spaces; following commands will be interpreted as additional arguments and therefore ignored
- replace ` and () to thwart command substitution, but still allow for $variable expansion; an underscore is harmless and doesn't mess with word splitting
- the eval retry was done because the original implementation ignorantly cut some glob alternations like @(foo|bar) into @(foo; I'm not sure whether that's an issue any longer, but let's keep the loop in there

The structure of the algorithm is now much cleaner, and I don't need the goto-emulating while loop any longer.
For --eval, we do some preprocessing for the chdir and negation prefixes (VAR=VAL don't make sense prior to cd and are not allowed before !), then wordsplit. Then we join the default path and just drop off the (now properly parsed) VAR=VAL assignments.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/commandName b/bin/commandName
--- a/bin/commandName
+++ b/bin/commandName
@@ -160,59 +160,47 @@ dropInterpreter()
     esac
 }
 
-while :	# Note: Use endless loop with break at the end to emulate goto; we cannot use a function, as we need to modify $@.
-do
-    # First eat individual preceding VAR=VAL arguments.
-    while [[ "$1" =~ ^[[:alpha:]_][[:alnum:]_]+=(\\[[:space:]]|[^[:space:]\\])*$ ]]; do shift; done
-
-    if [ "$isEval" ]; then
-	literalReplacement="$undefined"
-	literalReplacement="${literalReplacement//\\/\\\\}"
-	literalReplacement="${literalReplacement//&/\\&}"
-
-	# Extract COMMAND from preceding VAR=VAL inside the first remaining
-	# argument.
-	set -o noglob
-	COMMAND_SEPARATOR_COLLECTION=';&|'
-	netCommandLine="$(printf '%s\n' "${1:-${undefined}}" | sed \
-	    -e 1!d \
-	    -e "s/^[[:space:]]*\\([[:alpha:]_][[:alnum:]_]\\+=\\(\\\\[[:space:]]\\|[^[:space:]\\\\]\\)*[[:space:]]\\+\\)*\\(\"\\([^\"]\\+\\)\"\\|'\\([^']\\+\\)'\\|\\([^${COMMAND_SEPARATOR_COLLECTION}]\\+\\)\\)\\([${COMMAND_SEPARATOR_COLLECTION}].*\\)\\?$/\\4\\5\\6/" \
-	    -e t \
-	    -e "s#.*#${literalReplacement//#/\\#}#" \
-	    -e q
-	)"
-
-	# Drop a potential negation of the exit status.
-	netCommandLine="${netCommandLine#! }"
-
-	# DWIM: Drop the chdir in a "cd DIR && COMMAND" or "cd DIR; COMMAND" commandline.
-	if [[ "$netCommandLine" =~ ^cd[[:space:]] ]] && [[ "$*" =~ (\&\&|\;)[[:space:]]*([^[:space:]].*)$ ]]; then
-	    set -- "${BASH_REMATCH[2]}"
-	    continue
-	fi
-
-	# The eval may fail, e.g. with
-	# $ commandName --eval 'ls -t @(server|client)*.log?(.[0-9])'
-	#	-> ls -t @(server
-	# because of the incomplete glob. Therefore, error messages should be
-	# suppressed. As set -o noglob doesn't help, try removing arguments from the
-	# back for as long as possible and retry.
-	set -- '"$@"'   # Trick: To keep a "$@" argument intact, set the current arguments to that as a literal string.
-	until eval "set -- $netCommandLine" 2>/dev/null
-	do
-	    if [ "${netCommandLine/ //}" = "$netCommandLine" ]; then
-		break
-	    else
-		netCommandLine="${netCommandLine% *}"
-	    fi
-	done
-	if [ "$1" = '"$@"' ]; then
-	    # Drop the literal "$@" argument to avoid that it gets reported.
-	    shift
-	fi
+if [ "$isEval" ]; then
+    # DWIM: Drop the chdir in a "cd DIR && COMMAND" or "cd DIR; COMMAND" commandline.
+    if [[ "$1" =~ ^cd[[:space:]] ]] && [[ "$*" =~ (\&\&|\;)[[:space:]]*([^[:space:]].*)$ ]]; then
+	set -- "${BASH_REMATCH[2]}"
     fi
-    break
-done
+
+    netCommandLine="$*"
+
+    # Drop a potential negation of the exit status.
+    netCommandLine="${netCommandLine#!+([[:space:]])}"
+
+    # We don't want any command execution by the eval(), so any command pipeline
+    # separators need to be be defused. Replacing them with spaces automatically
+    # makes the parser stop at the first command.
+    netCommandLine="${netCommandLine//[;&|]/ }"
+
+    # The eval may fail; therefore, error messages should be suppressed. Try
+    # removing arguments from the back for as long as possible and retry.
+    set -- '"$@"'   # Trick: To keep a "$@" argument intact, set the current arguments to that as a literal string.
+    set -o noglob
+    # We want $variable expansion, but no `command` or $(command) substitution.
+    # Therefore, replace those with an underscore (that doesn't mess with the word
+    # splitting).
+    until eval "set -- ${netCommandLine//[\`()]/_}" 2>/dev/null
+    do
+	previousCommandLine="$netCommandLine"
+	netCommandLine="${netCommandLine%[[:space:]]*}"
+	[ "$netCommandLine" != "$previousCommandLine" ] || break
+    done
+
+    # Drop the literal "$@" argument to avoid that it gets reported.
+    typeset -a temp=()
+    for arg
+    do
+	[ "$1" = '"$@"' ] || temp+=("$arg")
+    done
+    set -- "${temp[@]}"
+fi
+
+# Eat individual preceding VAR=VAL arguments.
+while [[ "$1" =~ ^[[:alpha:]_][[:alnum:]_]+= ]]; do shift; done
 
 commandFilespec="$1"
 [ "$isDropInterpreter" ] && dropInterpreter "$@"
