dump-args: BUG: -- is included in the dump
Need to switch to long argument parsing, and omit the --.

diff --git a/bin/dump-args b/bin/dump-args
--- a/bin/dump-args
+++ b/bin/dump-args
@@ -8,11 +8,16 @@ HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-v|--verbose] [--] [ARG ...] [-?|-h|--help]'
 }
 isVerbose=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --verbose|-v)	shift; isVerbose=t;;
-    --)			shift;;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--verbose|-v)	shift; isVerbose=t;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 
 if [ "$isVerbose" ]; then
     shellquote()
