Do long argument parsing to support -- after -v|--invert

diff --git a/bin/emptydir b/bin/emptydir
--- a/bin/emptydir
+++ b/bin/emptydir
@@ -13,11 +13,16 @@ HELPTEXT
 printf 'Usage: %q %s\n' "$(basename "$1")" '[-v|--invert] [--] DIR [...] [-?|-h|--help]'
 }
 compareOp=-ne
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --invert|-v)	shift; compareOp=-eq;;
-    --)			shift;;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--invert|-v)	shift; compareOp=-eq;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -eq 0 ]; then
     printUsage "$0" >&2
     exit 2
