Minor: Consistently use printUsage(), add newline before bottom hint

diff --git a/bin/fileExtension b/bin/fileExtension
--- a/bin/fileExtension
+++ b/bin/fileExtension
@@ -11,7 +11,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -55,7 +55,7 @@ do
 	--split-all|-3)	shift; action=splitall;;
 	--splice|-c)	shift; action=splice; insertion="$1"; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
