headtail: Usability: Also enforce that NUM is a number

diff --git a/bin/headtail b/bin/headtail
--- a/bin/headtail
+++ b/bin/headtail
@@ -1,4 +1,5 @@
 #!/bin/bash
+shopt -qs extglob
 
 printUsage()
 {
@@ -14,7 +15,12 @@ lines=10
 header=auto
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --lines|-n)		shift; lines="$1"; shift;;
+    --lines|-n)		shift
+			case "$1" in
+			    +([0-9]))	lines="$1"; shift;;
+			    *)		printf '%s: invalid number of lines: %s\n' "$(basename "$0")" "$1"; exit 2;;
+			esac
+			;;
     --lines=*)		lines="${1#--lines=}"; shift;;
     --silent|--quiet|-q)
 			shift; header=no;;
