headtail: FIX: Race condition in processing the tempfile (after e95c406)
I had strange missing output in combination with my mount-data's error reporting:
> $ showFilesInUse --what data\ container -- /home/inkarkat/data | headtail --lines 20 --separator-cutline-file
Replacing the showFilesInUse with captured identical content made the output appear.
I traced this to a race condition between the capturing tee command and the headtail's processing.
In fact, as the capture is written as a preceding pipeline step, it's intention was to keep passing the original output to headtail, but the $tempFilespec was passed to headtail in order to show the temp filespec in the truncation message! If tee isn't quick enough to fill it, there's no output.
We can't just pass stdin to headtail via "-"; the truncation message wouldn't mention the temp file.
Instead, make the capture of stdin a separate step and do this before invoking headtail. We can then be sure that all of stdin has been captured.
Only downside is that if FILE(s) are passed before stdin, their contents now only appear after stdin is done, but that's an unlikely case.

(This corrects commit e95c4069da0ad243d45f5deb77f6cd3bacbad002)

System-info: Ubuntu 24.04.3 LTS, x86_64
Platform-info: bash 5.2.21(1)-release, Bats 1.10.0

diff --git a/bin/headtail b/bin/headtail
--- a/bin/headtail
+++ b/bin/headtail
@@ -124,7 +124,7 @@ passThrough()
 
 headTail()
 {
-    exec awk \
+    awk \
 	-v "lines=$lines" \
 	-v "isDuplicateIfShort=$isDuplicateIfShort" \
 	-v "separator=${separator//\\/\\\\}" \
@@ -232,25 +232,28 @@ FNR <= lines {
 headTailWithTempfile()
 {
     typeset -a filespecs=()
-    typeset -a captureCommand=()
+    local isStdinCaptured=
     local tempFilespec
     [ $# -gt 0 ] || set -- -
     local filespec; for filespec in "$@"
     do
-	if [ "$filespec" = - -a ${#captureCommand[@]} -eq 0 ]; then # AWK only processes stdin once, even if passed multiple times.
+	if [ "$filespec" = - ] && [ ! "$isStdinCaptured" ]; then # AWK only processes stdin once, even if passed multiple times.
+	    isStdinCaptured=t
+	    statusOnPassthrough=99  # Indicate full printing of inputs without truncation via exit status, so that we can decide whether to keep the temp file or not.
+
 	    local tempPrefix="${HEADTAIL_TEMP_PREFIX:-$(basename -- "$0")}"
 	    tempFilespec="$(mktemp --tmpdir "${tempPrefix}-XXXXXX" 2>/dev/null || echo "${TMPDIR:-/tmp}/${tempPrefix}.$$$RANDOM")"
-	    captureCommand=(tee -- "$tempFilespec")
-	    filespecs+=("$tempFilespec")
+	    tee -- "$tempFilespec" >/dev/null \
+		&& filespecs+=("$tempFilespec") \
+		|| return 3
 	else
 	    filespecs+=("$filespec")
 	fi
-	statusOnPassthrough=99	# Indicate full printing of inputs without truncation via exit status.
     done
 
-    eval '"${captureCommand[@]}"' "${captureCommand:+|}" 'headTail "${filespecs[@]}"'; status=$?
+    headTail "${filespecs[@]}"; status=$?
 
-    if [ $status -eq 99 -a ${#captureCommand[@]} -gt 0 ]; then
+    if [ $status -eq 99 ] && [ "$isStdinCaptured" ]; then
 	# (All) files were printed in full, i.e. no truncation happened; the cutline
 	# wasn't shown. The captured input can be removed.
 	rm -- "$tempFilespec"
