headtail: FIX: Parse multiple command-line arguments, observe --

diff --git a/bin/headtail b/bin/headtail
--- a/bin/headtail
+++ b/bin/headtail
@@ -16,19 +16,24 @@ HELPTEXT
 
 lines=$DEFAULT_LINES
 header=auto
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --lines|-n)		shift
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--lines|-n)	shift
 			case "$1" in
 			    +([0-9]))	lines="$1"; shift;;
 			    *)		printf '%s: invalid number of lines: %s\n' "$(basename "$0")" "$1"; exit 2;;
 			esac
 			;;
-    --lines=*)		lines="${1#--lines=}"; shift;;
-    --silent|--quiet|-q)
+	--lines=*)	lines="${1#--lines=}"; shift;;
+	--silent|--quiet|-q)
 			shift; header=no;;
-    --verbose|-v)	shift; header=yes;;
-esac
+	--verbose|-v)	shift; header=yes;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 
 exec awk \
     -v "lines=$lines" \
