ENH: Remove the captured input if the full contents have been printed
No need to leave behind a (potentially large and sensitive) temp file if its name has never been mentioned (in a cutline that wasn't printed).
Note: For simplicity, the AWK script only indicates whether _any_ truncation has happened, not if it happened on stdin in particular. This means that if FILE(s) other than stdin are passed as well (already unlikely), and those are truncated but stdin itself isn't, the temp file is kept even though it could be removed. We'll accept that small fuzziness to keep the implementation more understandable.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/headtail b/bin/headtail
--- a/bin/headtail
+++ b/bin/headtail
@@ -130,6 +130,7 @@ headTail()
 	-v "lineNumMarker=${lineNumMarker//\\/\\\\}" \
 	-v "fileMarker=${fileMarker//\\/\\\\}" \
 	-v "header=$header" \
+	-v "statusOnPassthrough=${statusOnPassthrough:-0}" \
 '
 function printHeadTail(      literalLineNumMarkerPattern, literalFileMarkerPattern, cutlineHalfWidth, cutline, filespec, omittedNum, start, i)
 {
@@ -156,6 +157,7 @@ function printHeadTail(      literalLineNumMarkerPattern, literalFileMarkerPatte
 	    if (separator ~ literalFileMarkerPattern) separator = gensub(literalFileMarkerPattern, filespec, "g", separator)
 
 	    print separator
+	    isTruncated = 1
 	}
     }
 
@@ -189,6 +191,9 @@ FNR == (lines + 1) {
 }
 ENDFILE {
     printHeadTail()
+}
+END {
+    exit(isTruncated ? 0 : statusOnPassthrough)
 }
 ' "$@"
 }
@@ -226,17 +231,29 @@ headTailWithTempfile()
 {
     typeset -a filespecs=()
     typeset -a captureCommand=()
+    local tempFilespec
     [ $# -gt 0 ] || set -- -
     local filespec; for filespec in "$@"
     do
 	if [ "$filespec" = - -a ${#captureCommand[@]} -eq 0 ]; then # AWK only processes stdin once, even if passed multiple times.
-	    filespec="$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TMPDIR:-/tmp}/$(basename -- "$0").$$$RANDOM")"
-	    captureCommand=(tee -- "$filespec")
+	    tempFilespec="$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TMPDIR:-/tmp}/$(basename -- "$0").$$$RANDOM")"
+	    captureCommand=(tee -- "$tempFilespec")
+	    filespecs+=("$tempFilespec")
+	else
+	    filespecs+=("$filespec")
 	fi
-	filespecs+=("$filespec")
+	statusOnPassthrough=99	# Indicate full printing of inputs without truncation via exit status.
     done
 
-    eval '"${captureCommand[@]}"' "${captureCommand:+|}" 'headTail "${filespecs[@]}"'
+    eval '"${captureCommand[@]}"' "${captureCommand:+|}" 'headTail "${filespecs[@]}"'; status=$?
+
+    if [ $status -eq 99 -a ${#captureCommand[@]} -gt 0 ]; then
+	# (All) files were printed in full, i.e. no truncation happened; the cutline
+	# wasn't shown. The captured input can be removed.
+	rm -- "$tempFilespec"
+	status=0
+    fi
+    return $status
 }
 
 $algorithm "$@"
