Robustness: Do not accept unknown -* options

diff --git a/bin/joinBy b/bin/joinBy
--- a/bin/joinBy
+++ b/bin/joinBy
@@ -98,6 +98,7 @@ do
 			set -- "${args[@]}"
 			break
 			;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
diff --git a/bin/printCounts b/bin/printCounts
--- a/bin/printCounts
+++ b/bin/printCounts
@@ -47,6 +47,7 @@ do
 	--empty)	shift; emptyText="$1"; shift;;
 	--joiner|-j)	shift; joiner="$1"; lastJoiner="$1"; shift;;
 	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
diff --git a/bin/userprompt b/bin/userprompt
--- a/bin/userprompt
+++ b/bin/userprompt
@@ -50,6 +50,7 @@ do
 	--keep-prompt|-k)	shift; clearPromptSequence=$'\n';;
 	--timeout|-t|--for)	shift; readArgs+=(-t "$1"); timeoutPlural=s; [ "$1" = 1 ] && timeoutPlural=; timeoutValue="${1} second$timeoutPlural"; shift;;
 	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
