logf: ENH: Allow Bash %q, submit single log even if format args < passed args, allow passing of prefix and suffix

diff --git a/bin/logf b/bin/logf
--- a/bin/logf
+++ b/bin/logf
@@ -1,4 +1,19 @@
-#!/bin/sh
+#!/bin/bash
+
+prefix=
+suffix=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--prefix|-p)	shift; prefix="$1"; shift;;
+	--suffix|-s)	shift; suffix="$1"; shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 
 format="$1"; shift
-printf "%s $format" "$(date '+%d-%b-%Y_%T.%N')" "$@"
+printf -v message "$format" "$@"
+exec log "${prefix}${message}${suffix}"
