ENH: Alllow reading from stdin via -
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/stringAsFilename b/bin/stringAsFilename
--- a/bin/stringAsFilename
+++ b/bin/stringAsFilename
@@ -4,23 +4,40 @@ shopt -qs extglob
 printUsage()
 {
     cat <<HELPTEXT
-Encode an arbitrary STRING for use as a filename; i.e. escape all forbidden
-characters, control the length, so that the result is a valid filename but
-enough uniqueness is kept. The only guarantee is that the same STRING will
-always lead to the same filename.
+Encode arbitrary TEXT (or text read from stdin via -) for use as a filename;
+i.e. escape all forbidden characters, control the length, so that the result is
+a valid filename but enough uniqueness is kept. The only guarantee is that the
+same TEXT will always lead to the same filename.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" 'STRING [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--] TEXT [...] [-?|-h|--help]'
+    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '- [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-esac
-if [ $# -eq 0 -o -z "$*" ]; then
+
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--)		shift; break;;
+	-)		break;; # For supporting special - FILE without prior --
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
+if [ $# -ne 1 ]; then
     printUsage "$0" >&2
     exit 2
 fi
 
-filename="${*//[^A-Za-z0-9]/_}"
+if [ "$1" = '-' ]; then
+    string=$(< /dev/stdin)
+    [ -n "$string" ] || exit 1
+else
+    string=${1?}
+fi
+
+
+filename="${string//[^A-Za-z0-9]/_}"
 filename="${filename//+(_)/_}"
 filename="${filename#_}"
 filename="${filename%_}"
