user[pre]query: Adapt: executionMarker now uses --older instead of --without
Use "datediff --get-short-usage" for obtaining the actual validity parameter values.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/userprequery b/bin/userprequery
--- a/bin/userprequery
+++ b/bin/userprequery
@@ -24,7 +24,7 @@ Returns $USERQUERY_EXIT_STATUS_NO_TERM / \$USERQUERY_EXIT_STATUS_NO_TERM if inpu
 terminal.
 HELPTEXT
     echo
-    printf 'Usage: $([USERQUERY_EXIT_STATUS_NO_TERM=99] [USERQUERY_INPUT=/dev/stdin] [USERQUERY_ERROR_OUTPUT=/dev/null] [USERQUERY_ALERT_SUBJECT=SUBJECT] [USERQUERY_ALERT_TIMESPAN=VALID-TIMESPAN|TIMESLOT] %q %s)"\n' "$(basename "$1")" '|| exit $?; select entry; do ...; done < "${USERQUERY_INPUT:-/dev/tty}"'
+    printf 'Usage: $([USERQUERY_EXIT_STATUS_NO_TERM=99] [USERQUERY_INPUT=/dev/stdin] [USERQUERY_ERROR_OUTPUT=/dev/null] [USERQUERY_ALERT_SUBJECT=SUBJECT] [USERQUERY_ALERT_TIMESPAN=%s] %q %s)"\n' "$(datediff --get-short-usage newer-older-parameters 2>/dev/null)" "$(basename "$1")" '|| exit $?; select entry; do ...; done < "${USERQUERY_INPUT:-/dev/tty}"'
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
@@ -38,7 +38,7 @@ if [ "$USERQUERY_ALERT_TIMESPAN" ]; then
 	executionMarker --base-type runtime --group userquery "$@"
     }
 
-    if marker --query "${USERQUERY_ALERT_SUBJECT:-default}" --without "$USERQUERY_ALERT_TIMESPAN"; then
+    if marker --query "${USERQUERY_ALERT_SUBJECT:-default}" --older "$USERQUERY_ALERT_TIMESPAN"; then
 	alert --exit-status 0 --success "${etcDir}/alert.mp3" --success-sigil '❓' --command-name "${USERQUERY_ALERT_SUBJECT:-Query}" --message "${USERQUERY_ALERT_SUBJECT:-An application} is waiting for your input again."
     fi
     marker --update "${USERQUERY_ALERT_SUBJECT:-default}"
